### ISSUE TITLE
Could not send message on channel admin: Template with id event:default does not exist

### ISSUE THREAD

**Issue by brian-labelle** [magespecialist/notifier-template#2]
- I have a channel called 'admin'
- I have a rule firing on event `sales_order_place_after`
- The Rule is set to Automatically select best template (if available)
![image](https://user-images.githubusercontent.com/8193356/37128344-4b53d4e6-223f-11e8-8e23-ec3656eda18f.png)

- I also have a template for Order placement, with identifier `event:sales_order_place_after`
![image](https://user-images.githubusercontent.com/8193356/37128372-80c2fb5c-223f-11e8-96e2-ef2460d638f2.png)
- When the event fires, I get the following message in the system log, and no notification is displayed
`Could not send message on channel ADMIN: Template with id event:default does not exist`
- This seems like two issues
1. It cannot find my template automatically
2. It cannot find the default template `event:default`

**Comment by phoenix128** [comment]
They seem to be 2 issues, you are right.

The default issue is because I mistyped the event name. Should be `event:_default` with the underscore.
Fixing it.

**Comment by phoenix128** [comment]
Should be fixed in 0.1.2, can you please confirm it?
